//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_order_detail
    {
        public int ID_orderDetails { get; set; }
        public Nullable<int> ID_order { get; set; }
        public Nullable<int> ID_Product { get; set; }
        public string Name_product { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<double> Total_money { get; set; }
    }
}
