//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Supplier
    {
        public int ID_Supplier { get; set; }
        public string Name_Supplier { get; set; }
        public string Store_Supplier { get; set; }
        public string Address_Supplier { get; set; }
        public Nullable<int> Tel_Supplier { get; set; }
    }
}
